### ISSUE TITLE
JN-MPPT-AL Buck Solar Charge Controller

### ISSUE THREAD

**Issue by MasterCATZ** [syssi/esphome-jnge-mppt-controller#30]
I have 30A chargers , I did buy them with wifi modules but could never get them to work 

I also can not seem to get this to work either 

most data I get is 
```
[12:21:53][D][sensor:124]: 'jn-mppt status operation mode id': Sending state -1.00000  with 0 decimals of accuracy
[12:21:53][D][text_sensor:067]: 'jn-mppt status operation mode': Sending state 'Offline'
...
[12:25:38][W][jnge_mppt_controller:460]: The device didn't respond to the last 15 status requests
```
anyway to test the MPPT RJ45 ports that they are actually working ? or could they have changed the pinout ? 

on the Elfin-EW11A
Pin 8 GND Brown X Pin 5 
Pin 7 VCC Blue X Pin 7
Pin 6  B-  Orange X Pin 1 
Pin 5 A+  Green X Pin 3 
Pin 4 Reload  Empty
Pin 3 Empty
Pin 2 Empty
Pin 1 Empty

![20220527_114803](https://user-images.githubusercontent.com/1857824/170614084-f832e6e0-0953-4cdc-aaa6-0d46d9cfeef0.jpg)

The schematic I have does show  Pins 
1/2 RS485-B RS485-B
3/4 RS485-A RS485-A
5/6 GND Powerground
7/8 +12VDC 12V/400mA

everything seems fine apart from no communication going on , all the wifi module does is reboot loops all 20+ of them ... 
I was really hoping to get this going , using these TTL turn RS485 module 485 to serial UART level mutual conversion hardware automatic flow control with esphome + Home Assistant 

https://www.aliexpress.com/item/1005002970555534.html

also currently testing with a spare  Wemos mini D1 , until esp32's arrive

**Comment by syssi** [comment]
Could you do two measurements:

1. Please measure the voltage between Pin 6 and Pin 8. You have to make sure the device is connected to a battery.
2. If there is no voltage at step 1 please measure the voltage between Pin 7 and Pin 8.

I'm aware of two pinouts of the RJ485 jack. Please compare the pinout of the JN-MPPT README with the JN-WIND README.

**Comment by syssi** [comment]
It looks like your WiFi module has the JN-WIND pinouts (may be the "new pinout"). Your solar charger has the JN-MPPT (may be the "old pinout"). If you prepare a new cable you should be able to get both solutions up and running.

**Comment by MasterCATZ** [comment]
using 568B

Green and Brown 
Green -13.8v Brown +13.8v

Brown stripe and Brown

**Comment by syssi** [comment]
This is what I've understood: 

You have measured the voltage between pin 6 and 8 and it's 13.8V. Could you measure the voltage between pin 5 (GND) and 6 (GND). It should be 0V.

If the above is true we have identified this pinout:

https://github.com/syssi/esphome-jnge-mppt-controller/blob/main/jnge_mppt_controller.md#rj45-jack

```
Pin 1: B-
Pin 2: B-
Pin 3: B-
Pin 4: B-
Pin 5: GND
Pin 6: GND
Pin 7: VCC
Pin 8: VCC
```

The next step is to attach the RS485 converter to the RX/TX pins of your ESP:

https://raw.githubusercontent.com/syssi/esphome-jnge-mppt-controller/main/images/circuit.jpg

The TX pin (of the RS485 converter) must blink periodically. If the RX pin blinks periodically you have to swap RX/TX. 

The RS485 lines must not be crossed. You have to attach "B-" (orange-white) to "B-" of the converter and "A+" (green-white) to "A+".

If everything is ready please provide a photo of your circuit/wiring.

**Comment by MasterCATZ** [comment]
yes the RS485 does blink

**Comment by syssi** [comment]
It's important the TX LED of the RS485 does blink. ;-) As next step I would like to see your wiring.

**Comment by MasterCATZ** [comment]
https://drive.google.com/drive/folders/17dD09No1H9q71I7gLnj-KpSR9HYUSzxJ?usp=sharing

**Comment by syssi** [comment]
I will try to replicate your setup to provide some details. The videos doesn't look good. I assume your setup crashs/reboots periodically.

**Comment by MasterCATZ** [comment]
no just wifi losses 

its just for testing , I have been waiting for shelves to arrive since last year ... 
Currently it is 
RS485 to TTL RX to RX on ESP8266
RS485 to TTL TX to TX on ESP8266

are you positive is should not be 

RS485 to TTL RX to TX on ESP8266
RS485 to TTL TX to RX on ESP8266

**Comment by syssi** [comment]
I've prepared a small demo. I've used this config example:

```
substitutions:
  name: jn-mppt
  status: "${name} status"
  config: "${name} config"
  external_components_source: github://syssi/esphome-jnge-mppt-controller@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:

api:
# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

jnge_mppt_controller:
  enable_fake_traffic: false
  suppress_battery_temperature_errors: false
  update_interval: 2s

binary_sensor:
  - platform: jnge_mppt_controller
    fan_running:
      name: "${status} fan running"
    load_detected:
      name: "${status} load detected"
    load:
      name: "${status} load"
    charging:
      name: "${status} charging"

sensor:
  - platform: jnge_mppt_controller
    # status
    firmware_version:
      name: "${status} firmware version"
    pv_voltage:
      name: "${status} pv voltage"
    battery_voltage:
      name: "${status} battery voltage"
    channel_a_current:
      name: "${status} channel a current"
    channel_b_current:
      name: "${status} channel b current"
    charging_current:
      name: "${status} charging current"
    charger_temperature:
      name: "${status} charger temperature"
    charging_power:
      name: "${status} charging power"
    discharge_power:
      name: "${status} discharge power"
    battery_capacity:
      name: "${status} battery capacity"
    operation_mode_id:
      name: "${status} operation mode id"
    discharge_current:
      name: "${status} discharge current"
    discharge_times:
      name: "${status} discharge times"
    total_charging_energy:
      name: "${status} total charging energy"
    total_discharge_energy:
      name: "${status} total discharge energy"
    battery_temperature:
      name: "${status} battery temperature"
    error_bitmask:
      name: "${status} error bitmask"
    controller_voltage_level:
      name: "${status} controller voltage level"
    pv_standby_voltage:
      name: "${status} pv standby voltage"
    controller_current_level:
      name: "${status} controller current level"
    battery_strings:
      name: "${status} battery strings"
    battery_temperature_compensation_voltage_point:
      name: "${status} battery temperature compensation voltage point"

    # config
    battery_overvoltage:
      name: "${config} battery overvoltage"
    charging_limit_voltage:
      name: "${config} charging limit voltage"
    battery_overvoltage_recovery:
      name: "${config} battery overvoltage recovery"
    equalizing_charging_voltage:
      name: "${config} equalizing charging voltage"
    boost_charging_voltage:
      name: "${config} boost charging voltage"
    boost_charging_return_voltage:
      name: "${config} boost charging return voltage"
    floating_charge_voltage:
      name: "${config} floating charge voltage"
    over_discharge_voltage:
      name: "${config} over discharge voltage"
    over_discharge_recovery_voltage:
      name: "${config} over discharge recovery voltage"
    battery_undervoltage:
      name: "${config} battery undervoltage"
    equalization_charging_time:
      name: "${config} equalization charging time"
    improve_charging_time:
      name: "${config} improve charging time"
    temperature_compensation_coefficient:
      name: "${config} temperature compensation coefficient"
    device_address:
      name: "${config} device address"
    light_control_on_voltage:
      name: "${config} light control on voltage"
    light_control_off_voltage:
      name: "${config} light control off voltage"
    light_control_on_period_1:
      name: "${config} light control on period 1"
    light_control_on_period_2:
      name: "${config} light control on period 2"
    load_turn_off_time:
      name: "${config} load turn off time"

switch:
  - platform: jnge_mppt_controller
    buzzer:
      name: "${config} buzzer"
    street_light_mode:
      name: "${config} street light mode"
    charging:
      name: "${config} charging"
    load:
      name: "${config} load"

text_sensor:
  - platform: jnge_mppt_controller
    battery_type:
      name: "${status} battery type"
    errors:
      name: "${status} errors"
    operation_mode:
      name: "${status} operation mode"

number:
  - platform: jnge_mppt_controller
    battery_overvoltage:
      name: "${config} battery overvoltage"
    charging_limit_voltage:
      name: "${config} charging limit voltage"
    battery_overvoltage_recovery:
      name: "${config} battery overvoltage recovery"
    equalizing_charging_voltage:
      name: "${config} equalizing charging voltage"
    boost_charging_voltage:
      name: "${config} boost charging voltage"
    boost_charging_return_voltage:
      name: "${config} boost charging return voltage"
    floating_charge_voltage:
      name: "${config} floating charge voltage"
    over_discharge_voltage:
      name: "${config} over discharge voltage"
    over_discharge_recovery_voltage:
      name: "${config} over discharge recovery voltage"
    battery_undervoltage:
      name: "${config} battery undervoltage"
    equalization_charging_time:
      name: "${config} equalization charging time"
    improve_charging_time:
      name: "${config} improve charging time"
    light_control_on_voltage:
      name: "${config} light control on voltage"
    light_control_off_voltage:
      name: "${config} light control off voltage"
    light_control_on_period_1:
      name: "${config} light control on period 1"
    light_control_on_period_2:
      name: "${config} light control on period 2"
    load_turn_off_time:
      name: "${config} load turn off time"
    battery_strings:
      name: "${config} battery strings"
```

I've used GPIO4 and GPIO5 (software serial) on purpose to be able to receive log message via UART0 (GPIO1, GPIO3). 

Please have a look at this video. The `update_interval` of the component is `2 seconds` therefore the component transmits one request per 2 seconds. The TX LED must blink every 2 seconds. Please compare this behavior with your TX LED. Something wrong is going on here with your setup. 

https://user-images.githubusercontent.com/2735933/170671014-d9f35611-1045-4d30-86ce-66e932a52b12.mp4
