### ISSUE TITLE
esphome changed over to one-wire

### ISSUE THREAD

**Issue by MasterCATZ** [syssi/esphome-jnge-mppt-controller#47]
ota: 
now needs a password as well

````
ota: 
  - password: secretstuff
    platform: esphome
````

*edit*
now looking through the code I guess all the dallas temp sensors where my stuff before I added a urt connection to the MPPT's 

so disregard the rest 

```
NFO Updating https://github.com/syssi/esphome-jnge-mppt-controller.git@main
Failed config

one_wire.unknown: [source /config/esphome/mpptcharger1.yaml:106]
  
  'one_wire' requires a 'platform' key but it was not specified.
  pin: GPIO2
  update_interval: 60s
````

1-Wire
Up until now, the dallas sensor platform contained the only 1-wire implementation in ESPHome. There had been requests to add support for other 1-wire based components, so [@ssieb](https://github.com/ssieb) has made a new top level [1-wire](https://esphome.io/components/one_wire) component that will allow for this. In doing so, the dallas sensor platform has been removed, and replaced with dallas_temp to allow for other Dallas sensors to be implemented that are not temperature sensors.
````
# Old
dallas:
  - pin: GPIOXX

sensor:
  - platform: dallas
    address: 0x1234567890abcdef
    name: "My Sensor"

# New
one_wire:
  - platform: gpio
    pin: GPIOXX

sensor:
  - platform: dallas_temp
    address: 0x1234567890abcdef
    name: "My Sensor"
````
